// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: child.proto

package me.lihongyu.utils.parser.test;

public final class ChildProtos {
  private ChildProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(ChildProtos.age);
    registry.add(ChildProtos.university);
    registry.add(ChildProtos.teacher);
    registry.add(ChildProtos.girlFriend);
    registry.add(ChildProtos.son);
    registry.add(ChildProtos.Boy.scoreInt);
    registry.add(ChildProtos.Boy.scoreDouble);
    registry.add(ChildProtos.Boy.scoreBool);
    registry.add(ChildProtos.Boy.scoreByte);
    registry.add(ChildProtos.Boy.scoreFloat);
    registry.add(ChildProtos.Boy.scoreLong);
    registry.add(ChildProtos.Boy.scoreEnum);
    registry.add(ChildProtos.Boy.parent);
    registry.add(ChildProtos.Boy.friend);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:biz.test.Child)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Child> {

    /**
     * <code>required string school = 1;</code>
     */
    boolean hasSchool();
    /**
     * <code>required string school = 1;</code>
     */
    java.lang.String getSchool();
    /**
     * <code>required string school = 1;</code>
     */
    com.google.protobuf.ByteString
        getSchoolBytes();

    /**
     * <code>optional string sex = 2;</code>
     */
    boolean hasSex();
    /**
     * <code>optional string sex = 2;</code>
     */
    java.lang.String getSex();
    /**
     * <code>optional string sex = 2;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    boolean hasAddressBook();
    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    AddressBookProtos.AddressBook getAddressBook();
    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    AddressBookProtos.AddressBookOrBuilder getAddressBookOrBuilder();
  }
  /**
   * Protobuf type {@code biz.test.Child}
   */
  public  static final class Child extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Child> implements
      // @@protoc_insertion_point(message_implements:biz.test.Child)
      ChildOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child.newBuilder() to construct.
    private Child(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<ChildProtos.Child, ?> builder) {
      super(builder);
    }
    private Child() {
      school_ = "";
      sex_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Child(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              school_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sex_ = bs;
              break;
            }
            case 26: {
              AddressBookProtos.AddressBook.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = addressBook_.toBuilder();
              }
              addressBook_ = input.readMessage(AddressBookProtos.AddressBook.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(addressBook_);
                addressBook_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChildProtos.internal_static_biz_test_Child_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChildProtos.internal_static_biz_test_Child_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChildProtos.Child.class, ChildProtos.Child.Builder.class);
    }

    private int bitField0_;
    public static final int SCHOOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object school_;
    /**
     * <code>required string school = 1;</code>
     */
    public boolean hasSchool() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string school = 1;</code>
     */
    public java.lang.String getSchool() {
      java.lang.Object ref = school_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          school_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string school = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchoolBytes() {
      java.lang.Object ref = school_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        school_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 2;
    private volatile java.lang.Object sex_;
    /**
     * <code>optional string sex = 2;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sex = 2;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sex_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sex = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_BOOK_FIELD_NUMBER = 3;
    private AddressBookProtos.AddressBook addressBook_;
    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    public boolean hasAddressBook() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    public AddressBookProtos.AddressBook getAddressBook() {
      return addressBook_ == null ? AddressBookProtos.AddressBook.getDefaultInstance() : addressBook_;
    }
    /**
     * <pre>
     *    optional AddressBook address_book3 = 4;
     * </pre>
     *
     * <code>optional .biz.test.AddressBook address_book = 3;</code>
     */
    public AddressBookProtos.AddressBookOrBuilder getAddressBookOrBuilder() {
      return addressBook_ == null ? AddressBookProtos.AddressBook.getDefaultInstance() : addressBook_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSchool()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddressBook()) {
        if (!getAddressBook().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<ChildProtos.Child>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, school_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getAddressBook());
      }
      extensionWriter.writeUntil(200, output);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, school_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddressBook());
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChildProtos.Child)) {
        return super.equals(obj);
      }
      ChildProtos.Child other = (ChildProtos.Child) obj;

      boolean result = true;
      result = result && (hasSchool() == other.hasSchool());
      if (hasSchool()) {
        result = result && getSchool()
            .equals(other.getSchool());
      }
      result = result && (hasSex() == other.hasSex());
      if (hasSex()) {
        result = result && getSex()
            .equals(other.getSex());
      }
      result = result && (hasAddressBook() == other.hasAddressBook());
      if (hasAddressBook()) {
        result = result && getAddressBook()
            .equals(other.getAddressBook());
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSchool()) {
        hash = (37 * hash) + SCHOOL_FIELD_NUMBER;
        hash = (53 * hash) + getSchool().hashCode();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex().hashCode();
      }
      if (hasAddressBook()) {
        hash = (37 * hash) + ADDRESS_BOOK_FIELD_NUMBER;
        hash = (53 * hash) + getAddressBook().hashCode();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChildProtos.Child parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Child parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Child parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Child parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Child parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Child parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Child parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChildProtos.Child parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChildProtos.Child parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChildProtos.Child parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChildProtos.Child parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChildProtos.Child parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChildProtos.Child prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code biz.test.Child}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          ChildProtos.Child, Builder> implements
        // @@protoc_insertion_point(builder_implements:biz.test.Child)
        ChildProtos.ChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChildProtos.internal_static_biz_test_Child_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChildProtos.internal_static_biz_test_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChildProtos.Child.class, ChildProtos.Child.Builder.class);
      }

      // Construct using me.lihongyu.test.ChildProtos.Child.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressBookFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        school_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sex_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (addressBookBuilder_ == null) {
          addressBook_ = null;
        } else {
          addressBookBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChildProtos.internal_static_biz_test_Child_descriptor;
      }

      @java.lang.Override
      public ChildProtos.Child getDefaultInstanceForType() {
        return ChildProtos.Child.getDefaultInstance();
      }

      @java.lang.Override
      public ChildProtos.Child build() {
        ChildProtos.Child result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ChildProtos.Child buildPartial() {
        ChildProtos.Child result = new ChildProtos.Child(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.school_ = school_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (addressBookBuilder_ == null) {
          result.addressBook_ = addressBook_;
        } else {
          result.addressBook_ = addressBookBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              ChildProtos.Child, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              ChildProtos.Child, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      @java.lang.Override
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              ChildProtos.Child, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              ChildProtos.Child, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChildProtos.Child) {
          return mergeFrom((ChildProtos.Child)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChildProtos.Child other) {
        if (other == ChildProtos.Child.getDefaultInstance()) return this;
        if (other.hasSchool()) {
          bitField0_ |= 0x00000001;
          school_ = other.school_;
          onChanged();
        }
        if (other.hasSex()) {
          bitField0_ |= 0x00000002;
          sex_ = other.sex_;
          onChanged();
        }
        if (other.hasAddressBook()) {
          mergeAddressBook(other.getAddressBook());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSchool()) {
          return false;
        }
        if (hasAddressBook()) {
          if (!getAddressBook().isInitialized()) {
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChildProtos.Child parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChildProtos.Child) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object school_ = "";
      /**
       * <code>required string school = 1;</code>
       */
      public boolean hasSchool() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string school = 1;</code>
       */
      public java.lang.String getSchool() {
        java.lang.Object ref = school_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            school_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string school = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSchoolBytes() {
        java.lang.Object ref = school_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          school_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string school = 1;</code>
       */
      public Builder setSchool(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        school_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string school = 1;</code>
       */
      public Builder clearSchool() {
        bitField0_ = (bitField0_ & ~0x00000001);
        school_ = getDefaultInstance().getSchool();
        onChanged();
        return this;
      }
      /**
       * <code>required string school = 1;</code>
       */
      public Builder setSchoolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        school_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>optional string sex = 2;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sex = 2;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sex_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sex = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sex = 2;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 2;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 2;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sex_ = value;
        onChanged();
        return this;
      }

      private AddressBookProtos.AddressBook addressBook_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressBookProtos.AddressBook, AddressBookProtos.AddressBook.Builder, AddressBookProtos.AddressBookOrBuilder> addressBookBuilder_;
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public boolean hasAddressBook() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public AddressBookProtos.AddressBook getAddressBook() {
        if (addressBookBuilder_ == null) {
          return addressBook_ == null ? AddressBookProtos.AddressBook.getDefaultInstance() : addressBook_;
        } else {
          return addressBookBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public Builder setAddressBook(AddressBookProtos.AddressBook value) {
        if (addressBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addressBook_ = value;
          onChanged();
        } else {
          addressBookBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public Builder setAddressBook(
          AddressBookProtos.AddressBook.Builder builderForValue) {
        if (addressBookBuilder_ == null) {
          addressBook_ = builderForValue.build();
          onChanged();
        } else {
          addressBookBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public Builder mergeAddressBook(AddressBookProtos.AddressBook value) {
        if (addressBookBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              addressBook_ != null &&
              addressBook_ != AddressBookProtos.AddressBook.getDefaultInstance()) {
            addressBook_ =
              AddressBookProtos.AddressBook.newBuilder(addressBook_).mergeFrom(value).buildPartial();
          } else {
            addressBook_ = value;
          }
          onChanged();
        } else {
          addressBookBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public Builder clearAddressBook() {
        if (addressBookBuilder_ == null) {
          addressBook_ = null;
          onChanged();
        } else {
          addressBookBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public AddressBookProtos.AddressBook.Builder getAddressBookBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAddressBookFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      public AddressBookProtos.AddressBookOrBuilder getAddressBookOrBuilder() {
        if (addressBookBuilder_ != null) {
          return addressBookBuilder_.getMessageOrBuilder();
        } else {
          return addressBook_ == null ?
              AddressBookProtos.AddressBook.getDefaultInstance() : addressBook_;
        }
      }
      /**
       * <pre>
       *    optional AddressBook address_book3 = 4;
       * </pre>
       *
       * <code>optional .biz.test.AddressBook address_book = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AddressBookProtos.AddressBook, AddressBookProtos.AddressBook.Builder, AddressBookProtos.AddressBookOrBuilder>
          getAddressBookFieldBuilder() {
        if (addressBookBuilder_ == null) {
          addressBookBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AddressBookProtos.AddressBook, AddressBookProtos.AddressBook.Builder, AddressBookProtos.AddressBookOrBuilder>(
                  getAddressBook(),
                  getParentForChildren(),
                  isClean());
          addressBook_ = null;
        }
        return addressBookBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:biz.test.Child)
    }

    // @@protoc_insertion_point(class_scope:biz.test.Child)
    private static final ChildProtos.Child DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChildProtos.Child();
    }

    public static ChildProtos.Child getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Child>
        PARSER = new com.google.protobuf.AbstractParser<Child>() {
      @java.lang.Override
      public Child parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Child(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Child> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ChildProtos.Child getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:biz.test.Boy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 speed = 1;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional int32 speed = 1;</code>
     */
    int getSpeed();
  }
  /**
   * Protobuf type {@code biz.test.Boy}
   */
  public  static final class Boy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:biz.test.Boy)
      BoyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Boy.newBuilder() to construct.
    private Boy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Boy() {
      speed_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Boy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              speed_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChildProtos.internal_static_biz_test_Boy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChildProtos.internal_static_biz_test_Boy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChildProtos.Boy.class, ChildProtos.Boy.Builder.class);
    }

    private int bitField0_;
    public static final int SPEED_FIELD_NUMBER = 1;
    private int speed_;
    /**
     * <code>optional int32 speed = 1;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 speed = 1;</code>
     */
    public int getSpeed() {
      return speed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, speed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, speed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChildProtos.Boy)) {
        return super.equals(obj);
      }
      ChildProtos.Boy other = (ChildProtos.Boy) obj;

      boolean result = true;
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (getSpeed()
            == other.getSpeed());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + getSpeed();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChildProtos.Boy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Boy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Boy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Boy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Boy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChildProtos.Boy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChildProtos.Boy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChildProtos.Boy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChildProtos.Boy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChildProtos.Boy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChildProtos.Boy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChildProtos.Boy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChildProtos.Boy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code biz.test.Boy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:biz.test.Boy)
        ChildProtos.BoyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChildProtos.internal_static_biz_test_Boy_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChildProtos.internal_static_biz_test_Boy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChildProtos.Boy.class, ChildProtos.Boy.Builder.class);
      }

      // Construct using me.lihongyu.test.ChildProtos.Boy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChildProtos.internal_static_biz_test_Boy_descriptor;
      }

      @java.lang.Override
      public ChildProtos.Boy getDefaultInstanceForType() {
        return ChildProtos.Boy.getDefaultInstance();
      }

      @java.lang.Override
      public ChildProtos.Boy build() {
        ChildProtos.Boy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ChildProtos.Boy buildPartial() {
        ChildProtos.Boy result = new ChildProtos.Boy(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChildProtos.Boy) {
          return mergeFrom((ChildProtos.Boy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChildProtos.Boy other) {
        if (other == ChildProtos.Boy.getDefaultInstance()) return this;
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChildProtos.Boy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChildProtos.Boy) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int speed_ ;
      /**
       * <code>optional int32 speed = 1;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 speed = 1;</code>
       */
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>optional int32 speed = 1;</code>
       */
      public Builder setSpeed(int value) {
        bitField0_ |= 0x00000001;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 speed = 1;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:biz.test.Boy)
    }

    // @@protoc_insertion_point(class_scope:biz.test.Boy)
    private static final ChildProtos.Boy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChildProtos.Boy();
    }

    public static ChildProtos.Boy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Boy>
        PARSER = new com.google.protobuf.AbstractParser<Boy>() {
      @java.lang.Override
      public Boy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Boy(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Boy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Boy> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ChildProtos.Boy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int SCORE_INT_FIELD_NUMBER = 130;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.Integer> scoreInt = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          0,
          java.lang.Integer.class,
          null);
    public static final int SCORE_DOUBLE_FIELD_NUMBER = 131;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.Double> scoreDouble = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          1,
          java.lang.Double.class,
          null);
    public static final int SCORE_BOOL_FIELD_NUMBER = 132;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.Boolean> scoreBool = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          2,
          java.lang.Boolean.class,
          null);
    public static final int SCORE_BYTE_FIELD_NUMBER = 133;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        com.google.protobuf.ByteString> scoreByte = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          3,
          com.google.protobuf.ByteString.class,
          null);
    public static final int SCORE_FLOAT_FIELD_NUMBER = 134;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.Float> scoreFloat = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          4,
          java.lang.Float.class,
          null);
    public static final int SCORE_LONG_FIELD_NUMBER = 135;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.Long> scoreLong = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          5,
          java.lang.Long.class,
          null);
    public static final int SCORE_ENUM_FIELD_NUMBER = 136;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        AddressBookProtos.Person.PhoneType> scoreEnum = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          6,
          AddressBookProtos.Person.PhoneType.class,
          null);
    public static final int PARENT_FIELD_NUMBER = 137;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        java.lang.String> parent = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          7,
          java.lang.String.class,
          null);
    public static final int FRIEND_FIELD_NUMBER = 138;
    /**
     * <code>extend .biz.test.Child { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        ChildProtos.Child,
        AddressBookProtos.Person> friend = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          ChildProtos.Boy.getDefaultInstance(),
          8,
          AddressBookProtos.Person.class,
          AddressBookProtos.Person.getDefaultInstance());
  }

  public static final int AGE_FIELD_NUMBER = 140;
  /**
   * <code>extend .biz.test.Child { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ChildProtos.Child,
      java.lang.Integer> age = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int UNIVERSITY_FIELD_NUMBER = 150;
  /**
   * <code>extend .biz.test.Child { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ChildProtos.Child,
      java.lang.String> university = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TEACHER_FIELD_NUMBER = 160;
  /**
   * <code>extend .biz.test.Child { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ChildProtos.Child,
      AddressBookProtos.Person> teacher = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        AddressBookProtos.Person.class,
        AddressBookProtos.Person.getDefaultInstance());
  public static final int GIRLFRIEND_FIELD_NUMBER = 180;
  /**
   * <code>extend .biz.test.Child { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ChildProtos.Child,
      AddressBookProtos.Person> girlFriend = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        AddressBookProtos.Person.class,
        AddressBookProtos.Person.getDefaultInstance());
  public static final int SON_FIELD_NUMBER = 190;
  /**
   * <code>extend .biz.test.Child { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ChildProtos.Child,
      ChildProtos.Boy> son = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ChildProtos.Boy.class,
        ChildProtos.Boy.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_biz_test_Child_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_biz_test_Child_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_biz_test_Boy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_biz_test_Boy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013child.proto\022\010biz.test\032\021addressbook.pro" +
      "to\"X\n\005Child\022\016\n\006school\030\001 \002(\t\022\013\n\003sex\030\002 \001(\t" +
      "\022+\n\014address_book\030\003 \001(\0132\025.biz.test.Addres" +
      "sBook*\005\010d\020\310\001\"\222\003\n\003Boy\022\r\n\005speed\030\001 \001(\0052#\n\ts" +
      "core_int\022\017.biz.test.Child\030\202\001 \001(\0052&\n\014scor" +
      "e_double\022\017.biz.test.Child\030\203\001 \001(\0012$\n\nscor" +
      "e_bool\022\017.biz.test.Child\030\204\001 \001(\0102$\n\nscore_" +
      "byte\022\017.biz.test.Child\030\205\001 \001(\0142%\n\013score_fl" +
      "oat\022\017.biz.test.Child\030\206\001 \001(\0022$\n\nscore_lon" +
      "g\022\017.biz.test.Child\030\207\001 \001(\0032@\n\nscore_enum\022" +
      "\017.biz.test.Child\030\210\001 \001(\0162\032.biz.test.Perso" +
      "n.PhoneType2 \n\006parent\022\017.biz.test.Child\030\211" +
      "\001 \001(\t22\n\006friend\022\017.biz.test.Child\030\212\001 \001(\0132" +
      "\020.biz.test.Person:\035\n\003age\022\017.biz.test.Chil" +
      "d\030\214\001 \001(\005:$\n\nuniversity\022\017.biz.test.Child\030" +
      "\226\001 \001(\t:3\n\007teacher\022\017.biz.test.Child\030\240\001 \001(" +
      "\0132\020.biz.test.Person:6\n\ngirlFriend\022\017.biz." +
      "test.Child\030\264\001 \001(\0132\020.biz.test.Person:,\n\003s" +
      "on\022\017.biz.test.Child\030\276\001 \001(\0132\r.biz.test.Bo" +
      "yB(\n\031com.autonavi.snowman.testB\013ChildPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AddressBookProtos.getDescriptor(),
        }, assigner);
    internal_static_biz_test_Child_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_biz_test_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_biz_test_Child_descriptor,
        new java.lang.String[] { "School", "Sex", "AddressBook", });
    internal_static_biz_test_Boy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_biz_test_Boy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_biz_test_Boy_descriptor,
        new java.lang.String[] { "Speed", });
    age.internalInit(descriptor.getExtensions().get(0));
    university.internalInit(descriptor.getExtensions().get(1));
    teacher.internalInit(descriptor.getExtensions().get(2));
    girlFriend.internalInit(descriptor.getExtensions().get(3));
    son.internalInit(descriptor.getExtensions().get(4));
    AddressBookProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
